<?php

namespace Fuel\Migrations;

class Create_expense_tables{
    public function up(){
        \DBUtil::create_table("user",[
            "id"=>[
            "type"=>"int",
            "constraint"=>11,
            "auto_increment"=>true,
            ],  
            "username"=>[
                "type"=>"varchar",
                "constraint"=>50,
            ],
            "password"=>[
                "type"=>"varchar",
                "constraint"=>255,
            ],
            "created_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
            "updated_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
        ],["id"]);
        \DBUtil::create_index(
            "user",
            ["username"],
            "uq_user_username",
            "unique"
        );
        \DBUtil::create_table("budget",[
            "id"=>[
                "type"=>"int",
                "constraint"=>11,
                "auto_increment"=>true,
            ],
            "user_id"=>[
                "type"=>"int",
                "constraint"=>11,
            ],
            "year"=>[
                "type"=>"int",
                "constraint"=>4,
                "default"=>0,
            ],
            "month"=>[
                "type"=>"int",
                "constraint"=>2,
                "default"=>0,
            ],
            "amount"=>[
                "type"=>"int",
                "constraint"=>11,
                "default"=>0,
            ],
            "created_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
            "updated_at"=>[
                "type"=>"datetime",
                "null"=>true
            ],
        ],["id"]);
        \DBUtil::create_index(
            "budget",
            ["user_id","year","month"],
            "uq_category_user_year_month",
            "unique"

        );
        \DBUtil::create_table("expense",[
            "id"=>[
                "type"=>"int",
                "constraint"=>11,
                "auto_increment"=>true,
            ],
            "user_id"=>[
                "type"=>"int",
                "constraint"=>11,
                "default"=>0,
            ],
            "category_id"=>[
                "type"=>"int",
                "constraint"=>11,
                "default"=>0,
            ],
            "title"=>[
                "type"=>"varchar",
                "constraint"=>100,
            ],
            "amount"=>[
                "type"=>"int",
                "constraint"=>11,
                "default"=>0,
            ],
            "expense_date"=>[
                "type"=>"date",
            ],
            "memo"=>[
                "type"=>"varchar",
                "constraint"=>255,
                "null"=>true,
            ],
            "created_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
            "updated_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
        ],["id"]);
        \DBUtil::create_index(
            "expense",
            ["user_id","expense_date"],
            "idx_expense_user_date"
        );
        \DBUtil::create_index(
            "expense",
            ["category_id"],
            "idx_expense_category"
        );
        \DBUtil::create_table("category",[
            "id"=>[
                "type"=>"int",
                "constraint"=>11,
                "auto_increment"=>true,
            ],
            "user_id"=>[
                "type"=>"int",
                "constraint"=>11,
                "default"=>0,
            ],
            "name"=>[
                "type"=>"varchar",
                "constraint"=>50,
            ],
            "created_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
            "updated_at"=>[
                "type"=>"datetime",
                "null"=>true,
            ],
        ],["id"]);
    \DBUtil::create_index(
        "category",
        ["user_id","name"],
        "uq_category_user_name",
        "unique"
    );
    }

    public function down(){
        \DBUtil::drop_table("expense");
        \DBUtil::drop_table("category");
        \DBUtil::drop_table("budget");
        \DBUtil::drop_table("user");
    }
}